version: '3' #Docker-compose version
services: # Lista de servicios
  flask_app: #servicio/app de flask
    build: # Lista de par√°metros desde los cuales construir
      context: . #contexto
      dockerfile: Dockerfile #archivo de Dockerfile
    ports: #puerto contenedor:puerto host
      - "5004:5004"
    restart: always #en caso de error o falla 